# Generated by Django 3.1 on 2021-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_post_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_name',
            new_name='phone',
        ),
    ]
