# Generated by Django 3.1 on 2021-01-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20210107_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phone',
            new_name='first_name',
        ),
    ]
